# Generated by Django 2.2 on 2019-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conteudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='titulo')),
                ('email', models.TextField(max_length=50, verbose_name='texto')),
                ('senha', models.CharField(max_length=50, verbose_name='autor')),
            ],
        ),
    ]
