# Generated by Django 2.2 on 2019-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoDjango', '0002_conteudos'),
    ]

    operations = [
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('assunto', models.CharField(max_length=50, verbose_name='assunto')),
                ('conteudo', models.TextField(max_length=50, verbose_name='conteudo')),
            ],
        ),
        migrations.RenameField(
            model_name='conteudos',
            old_name='nome',
            new_name='titulo',
        ),
    ]
