# Generated by Django 2.2 on 2019-05-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoDjango', '0003_auto_20190512_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conteudos',
            new_name='conteudo',
        ),
    ]
