# Generated by Django 2.2 on 2019-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoDjango', '0004_auto_20190512_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conteudo',
            old_name='senha',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='conteudo',
            old_name='email',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='contato',
            name='conteudo',
            field=models.TextField(max_length=200, verbose_name='conteudo'),
        ),
    ]
